"""Expose ComfyUI node mappings and front-end resources."""

WEB_DIRECTORY = "."

from .nodes import (  # noqa: F401
    NODE_CLASS_MAPPINGS as DIRECTOR_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as DIRECTOR_NODE_DISPLAY_NAME_MAPPINGS,
)
from .qwen3_vl_nodes import (  # noqa: F401
    NODE_CLASS_MAPPINGS as QWEN3_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as QWEN3_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **DIRECTOR_NODE_CLASS_MAPPINGS,
    **QWEN3_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **DIRECTOR_NODE_DISPLAY_NAME_MAPPINGS,
    **QWEN3_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
